### ISSUE TITLE
Wrong page number when multiple pages exists in output

### ISSUE THREAD

**Issue by trisii** [npxtune/database_uni#4]
If the output has more than one page, it will default to page number 5 by default. 
![ZdexyTB](https://github.com/npxtune/database_uni/assets/123873454/253c4e22-4eef-4783-b248-bfde5a65b287)

**Comment by timdevorg** [comment]
Thanks, I did not notice that before! Will be fixing this with the next pull request.

**Comment by timdevorg** [comment]
Fixed with PR #7
